const foodImagePaths = [
  'assets/images/samosa/samosa9.jpg',
  'assets/images/samosa/samosa8.jpg',
  'assets/images/samosa/samosa7.jpg',
  'assets/images/samosa/samosa6.jpg',
  'assets/images/samosa/samosa5.jpg',
  'assets/images/samosa/samosa4.jpg',
  'assets/images/samosa/samosa3.jpg',
  'assets/images/samosa/samosa22.jpg',
  'assets/images/samosa/samosa21.jpg',
  'assets/images/samosa/samosa20.jpg',
  'assets/images/samosa/samosa2.jpg',
  'assets/images/samosa/samosa19.jpg',
  'assets/images/samosa/samosa18.jpg',
  'assets/images/samosa/samosa17.jpg',
  'assets/images/samosa/samosa16.jpg',
  'assets/images/samosa/samosa15.jpg',
  'assets/images/samosa/samosa14.jpg',
  'assets/images/samosa/samosa13.jpg',
  'assets/images/samosa/samosa12.jpg',
  'assets/images/samosa/samosa11.jpg',
  'assets/images/samosa/samosa10.jpg',
  'assets/images/samosa/samosa1.jpg',
  'assets/images/rice/rice9.jpg',
  'assets/images/rice/rice8.jpg',
  'assets/images/rice/rice7.jpg',
  'assets/images/rice/rice6.jpg',
  'assets/images/rice/rice5.jpg',
  'assets/images/rice/rice4.jpg',
  'assets/images/rice/rice35.jpg',
  'assets/images/rice/rice34.jpg',
  'assets/images/rice/rice33.jpg',
  'assets/images/rice/rice32.jpg',
  'assets/images/rice/rice31.jpg',
  'assets/images/rice/rice30.jpg',
  'assets/images/rice/rice3.jpg',
  'assets/images/rice/rice29.jpg',
  'assets/images/rice/rice28.jpg',
  'assets/images/rice/rice27.jpg',
  'assets/images/rice/rice26.jpg',
  'assets/images/rice/rice25.jpg',
  'assets/images/rice/rice24.jpg',
  'assets/images/rice/rice23.jpg',
  'assets/images/rice/rice22.jpg',
  'assets/images/rice/rice21.jpg',
  'assets/images/rice/rice20.jpg',
  'assets/images/rice/rice2.jpg',
  'assets/images/rice/rice19.jpg',
  'assets/images/rice/rice18.jpg',
  'assets/images/rice/rice17.jpg',
  'assets/images/rice/rice16.jpg',
  'assets/images/rice/rice15.jpg',
  'assets/images/rice/rice14.jpg',
  'assets/images/rice/rice13.jpg',
  'assets/images/rice/rice12.jpg',
  'assets/images/rice/rice11.jpg',
  'assets/images/rice/rice10.jpg',
  'assets/images/rice/rice1.jpg',
  'assets/images/pasta/pasta9.jpg',
  'assets/images/pasta/pasta8.jpg',
  'assets/images/pasta/pasta7.jpg',
  'assets/images/pasta/pasta6.jpg',
  'assets/images/pasta/pasta5.jpg',
  'assets/images/pasta/pasta4.jpg',
  'assets/images/pasta/pasta34.jpg',
  'assets/images/pasta/pasta33.jpg',
  'assets/images/pasta/pasta32.jpg',
  'assets/images/pasta/pasta31.jpg',
  'assets/images/pasta/pasta30.jpg',
  'assets/images/pasta/pasta3.jpg',
  'assets/images/pasta/pasta29.jpg',
  'assets/images/pasta/pasta28.jpg',
  'assets/images/pasta/pasta27.jpg',
  'assets/images/pasta/pasta26.jpg',
  'assets/images/pasta/pasta25.jpg',
  'assets/images/pasta/pasta24.jpg',
  'assets/images/pasta/pasta23.jpg',
  'assets/images/pasta/pasta22.jpg',
  'assets/images/pasta/pasta21.jpg',
  'assets/images/pasta/pasta20.jpg',
  'assets/images/pasta/pasta2.jpg',
  'assets/images/pasta/pasta19.jpg',
  'assets/images/pasta/pasta18.jpg',
  'assets/images/pasta/pasta17.jpg',
  'assets/images/pasta/pasta16.jpg',
  'assets/images/pasta/pasta15.jpg',
  'assets/images/pasta/pasta14.jpg',
  'assets/images/pasta/pasta13.jpg',
  'assets/images/pasta/pasta12.jpg',
  'assets/images/pasta/pasta11.jpg',
  'assets/images/pasta/pasta10.jpg',
  'assets/images/pasta/pasta1.jpg',
  'assets/images/pizza/pizza95.jpg',
  'assets/images/pizza/pizza94.jpg',
  'assets/images/pizza/pizza93.jpg',
  'assets/images/pizza/pizza92.jpg',
  'assets/images/pizza/pizza91.jpg',
  'assets/images/pizza/pizza90.jpg',
  'assets/images/pizza/pizza9.jpg',
  'assets/images/pizza/pizza89.jpg',
  'assets/images/pizza/pizza88.jpg',
  'assets/images/pizza/pizza87.jpg',
  'assets/images/pizza/pizza86.jpg',
  'assets/images/pizza/pizza85.jpg',
  'assets/images/pizza/pizza84.jpg',
  'assets/images/pizza/pizza83.jpg',
  'assets/images/pizza/pizza82.jpg',
  'assets/images/pizza/pizza81.jpg',
  'assets/images/pizza/pizza80.jpg',
  'assets/images/pizza/pizza8.jpg',
  'assets/images/pizza/pizza79.jpg',
  'assets/images/pizza/pizza78.jpg',
  'assets/images/pizza/pizza77.jpg',
  'assets/images/pizza/pizza76.jpg',
  'assets/images/pizza/pizza75.jpg',
  'assets/images/pizza/pizza74.jpg',
  'assets/images/pizza/pizza73.jpg',
  'assets/images/pizza/pizza72.jpg',
  'assets/images/pizza/pizza71.jpg',
  'assets/images/pizza/pizza70.jpg',
  'assets/images/pizza/pizza7.jpg',
  'assets/images/pizza/pizza69.jpg',
  'assets/images/pizza/pizza68.jpg',
  'assets/images/pizza/pizza67.jpg',
  'assets/images/pizza/pizza66.jpg',
  'assets/images/pizza/pizza65.jpg',
  'assets/images/pizza/pizza64.jpg',
  'assets/images/pizza/pizza63.jpg',
  'assets/images/pizza/pizza62.jpg',
  'assets/images/pizza/pizza61.jpg',
  'assets/images/pizza/pizza60.jpg',
  'assets/images/pizza/pizza6.jpg',
  'assets/images/pizza/pizza59.jpg',
  'assets/images/pizza/pizza58.jpg',
  'assets/images/pizza/pizza57.jpg',
  'assets/images/pizza/pizza56.jpg',
  'assets/images/pizza/pizza55.jpg',
  'assets/images/pizza/pizza54.jpg',
  'assets/images/pizza/pizza53.jpg',
  'assets/images/pizza/pizza52.jpg',
  'assets/images/pizza/pizza51.jpg',
  'assets/images/pizza/pizza50.jpg',
  'assets/images/pizza/pizza5.jpg',
  'assets/images/pizza/pizza49.jpg',
  'assets/images/pizza/pizza48.jpg',
  'assets/images/pizza/pizza47.jpg',
  'assets/images/pizza/pizza46.jpg',
  'assets/images/pizza/pizza45.jpg',
  'assets/images/pizza/pizza44.jpg',
  'assets/images/pizza/pizza43.jpg',
  'assets/images/pizza/pizza42.jpg',
  'assets/images/pizza/pizza41.jpg',
  'assets/images/pizza/pizza40.jpg',
  'assets/images/pizza/pizza4.jpg',
  'assets/images/pizza/pizza39.jpg',
  'assets/images/pizza/pizza38.jpg',
  'assets/images/pizza/pizza37.jpg',
  'assets/images/pizza/pizza36.jpg',
  'assets/images/pizza/pizza35.jpg',
  'assets/images/pizza/pizza34.jpg',
  'assets/images/pizza/pizza33.jpg',
  'assets/images/pizza/pizza32.jpg',
  'assets/images/pizza/pizza31.jpg',
  'assets/images/pizza/pizza30.jpg',
  'assets/images/pizza/pizza3.jpg',
  'assets/images/pizza/pizza29.jpg',
  'assets/images/pizza/pizza28.jpg',
  'assets/images/pizza/pizza27.jpg',
  'assets/images/pizza/pizza26.jpg',
  'assets/images/pizza/pizza25.jpg',
  'assets/images/pizza/pizza24.jpg',
  'assets/images/pizza/pizza23.jpg',
  'assets/images/pizza/pizza22.jpg',
  'assets/images/pizza/pizza21.jpg',
  'assets/images/pizza/pizza20.jpg',
  'assets/images/pizza/pizza2.jpg',
  'assets/images/pizza/pizza19.jpg',
  'assets/images/pizza/pizza18.jpg',
  'assets/images/pizza/pizza17.jpg',
  'assets/images/pizza/pizza16.jpg',
  'assets/images/pizza/pizza15.jpg',
  'assets/images/pizza/pizza14.jpg',
  'assets/images/pizza/pizza13.jpg',
  'assets/images/pizza/pizza12.jpg',
  'assets/images/pizza/pizza11.jpg',
  'assets/images/pizza/pizza10.jpg',
  'assets/images/pizza/pizza1.jpg',
  'assets/images/idly/idly9.jpg',
  'assets/images/idly/idly8.jpg',
  'assets/images/idly/idly77.jpg',
  'assets/images/idly/idly76.jpg',
  'assets/images/idly/idly75.jpg',
  'assets/images/idly/idly74.jpg',
  'assets/images/idly/idly73.jpg',
  'assets/images/idly/idly72.jpg',
  'assets/images/idly/idly71.jpg',
  'assets/images/idly/idly70.jpg',
  'assets/images/idly/idly7.jpg',
  'assets/images/idly/idly69.jpg',
  'assets/images/idly/idly68.jpg',
  'assets/images/idly/idly67.jpg',
  'assets/images/idly/idly66.jpg',
  'assets/images/idly/idly65.jpg',
  'assets/images/idly/idly64.jpg',
  'assets/images/idly/idly63.jpg',
  'assets/images/idly/idly62.jpg',
  'assets/images/idly/idly61.jpg',
  'assets/images/idly/idly60.jpg',
  'assets/images/idly/idly6.jpg',
  'assets/images/idly/idly59.jpg',
  'assets/images/idly/idly58.jpg',
  'assets/images/idly/idly57.jpg',
  'assets/images/idly/idly56.jpg',
  'assets/images/idly/idly55.jpg',
  'assets/images/idly/idly54.jpg',
  'assets/images/idly/idly53.jpg',
  'assets/images/idly/idly52.jpg',
  'assets/images/idly/idly51.jpg',
  'assets/images/idly/idly50.jpg',
  'assets/images/idly/idly5.jpg',
  'assets/images/idly/idly49.jpg',
  'assets/images/idly/idly48.jpg',
  'assets/images/idly/idly47.jpg',
  'assets/images/idly/idly46.jpg',
  'assets/images/idly/idly45.jpg',
  'assets/images/idly/idly44.jpg',
  'assets/images/idly/idly43.jpg',
  'assets/images/idly/idly42.jpg',
  'assets/images/idly/idly41.jpg',
  'assets/images/idly/idly40.jpg',
  'assets/images/idly/idly4.jpg',
  'assets/images/idly/idly39.jpg',
  'assets/images/idly/idly38.jpg',
  'assets/images/idly/idly37.jpg',
  'assets/images/idly/idly36.jpg',
  'assets/images/idly/idly35.jpg',
  'assets/images/idly/idly34.jpg',
  'assets/images/idly/idly33.jpg',
  'assets/images/idly/idly32.jpg',
  'assets/images/idly/idly31.jpg',
  'assets/images/idly/idly30.jpg',
  'assets/images/idly/idly3.jpg',
  'assets/images/idly/idly29.jpg',
  'assets/images/idly/idly28.jpg',
  'assets/images/idly/idly27.jpg',
  'assets/images/idly/idly26.jpg',
  'assets/images/idly/idly25.jpg',
  'assets/images/idly/idly24.jpg',
  'assets/images/idly/idly23.jpg',
  'assets/images/idly/idly22.jpg',
  'assets/images/idly/idly21.jpg',
  'assets/images/idly/idly20.jpg',
  'assets/images/idly/idly2.jpg',
  'assets/images/idly/idly19.jpg',
  'assets/images/idly/idly18.jpg',
  'assets/images/idly/idly17.jpg',
  'assets/images/idly/idly16.jpg',
  'assets/images/idly/idly15.jpg',
  'assets/images/idly/idly14.jpg',
  'assets/images/idly/idly13.jpg',
  'assets/images/idly/idly12.jpg',
  'assets/images/idly/idly11.jpg',
  'assets/images/idly/idly10.jpg',
  'assets/images/idly/idly1.jpg',
  'assets/images/dosa/dosa9.jpg',
  'assets/images/dosa/dosa83.jpg',
  'assets/images/dosa/dosa82.jpg',
  'assets/images/dosa/dosa81.jpg',
  'assets/images/dosa/dosa80.jpg',
  'assets/images/dosa/dosa8.jpg',
  'assets/images/dosa/dosa79.jpg',
  'assets/images/dosa/dosa78.jpg',
  'assets/images/dosa/dosa77.jpg',
  'assets/images/dosa/dosa76.jpg',
  'assets/images/dosa/dosa75.jpg',
  'assets/images/dosa/dosa74.jpg',
  'assets/images/dosa/dosa73.jpg',
  'assets/images/dosa/dosa72.jpg',
  'assets/images/dosa/dosa71.jpg',
  'assets/images/dosa/dosa70.jpg',
  'assets/images/dosa/dosa7.jpg',
  'assets/images/dosa/dosa69.jpg',
  'assets/images/dosa/dosa68.jpg',
  'assets/images/dosa/dosa67.jpg',
  'assets/images/dosa/dosa66.jpg',
  'assets/images/dosa/dosa65.jpg',
  'assets/images/dosa/dosa64.jpg',
  'assets/images/dosa/dosa63.jpg',
  'assets/images/dosa/dosa62.jpg',
  'assets/images/dosa/dosa61.jpg',
  'assets/images/dosa/dosa60.jpg',
  'assets/images/dosa/dosa6.jpg',
  'assets/images/dosa/dosa59.jpg',
  'assets/images/dosa/dosa58.jpg',
  'assets/images/dosa/dosa57.jpg',
  'assets/images/dosa/dosa56.jpg',
  'assets/images/dosa/dosa55.jpg',
  'assets/images/dosa/dosa54.jpg',
  'assets/images/dosa/dosa53.jpg',
  'assets/images/dosa/dosa52.jpg',
  'assets/images/dosa/dosa51.jpg',
  'assets/images/dosa/dosa50.jpg',
  'assets/images/dosa/dosa5.jpg',
  'assets/images/dosa/dosa49.jpg',
  'assets/images/dosa/dosa48.jpg',
  'assets/images/dosa/dosa47.jpg',
  'assets/images/dosa/dosa46.jpg',
  'assets/images/dosa/dosa45.jpg',
  'assets/images/dosa/dosa44.jpg',
  'assets/images/dosa/dosa43.jpg',
  'assets/images/dosa/dosa42.jpg',
  'assets/images/dosa/dosa41.jpg',
  'assets/images/dosa/dosa40.jpg',
  'assets/images/dosa/dosa4.jpg',
  'assets/images/dosa/dosa39.jpg',
  'assets/images/dosa/dosa38.jpg',
  'assets/images/dosa/dosa37.jpg',
  'assets/images/dosa/dosa36.jpg',
  'assets/images/dosa/dosa35.jpg',
  'assets/images/dosa/dosa34.jpg',
  'assets/images/dosa/dosa33.jpg',
  'assets/images/dosa/dosa32.jpg',
  'assets/images/dosa/dosa31.jpg',
  'assets/images/dosa/dosa30.jpg',
  'assets/images/dosa/dosa3.jpg',
  'assets/images/dosa/dosa29.jpg',
  'assets/images/dosa/dosa28.jpg',
  'assets/images/dosa/dosa27.jpg',
  'assets/images/dosa/dosa26.jpg',
  'assets/images/dosa/dosa25.jpg',
  'assets/images/dosa/dosa24.jpg',
  'assets/images/dosa/dosa23.jpg',
  'assets/images/dosa/dosa22.jpg',
  'assets/images/dosa/dosa21.jpg',
  'assets/images/dosa/dosa20.jpg',
  'assets/images/dosa/dosa19.jpg',
  'assets/images/dosa/dosa2.jpg',
  'assets/images/dosa/dosa18.jpg',
  'assets/images/dosa/dosa17.jpg',
  'assets/images/dosa/dosa16.jpg',
  'assets/images/dosa/dosa15.jpg',
  'assets/images/dosa/dosa14.jpg',
  'assets/images/dosa/dosa13.jpg',
  'assets/images/dosa/dosa12.jpg',
  'assets/images/dosa/dosa11.jpg',
  'assets/images/dosa/dosa10.jpg',
  'assets/images/dosa/dosa1.jpg',
  'assets/images/dessert/dessert9.jpg',
  'assets/images/dessert/dessert8.jpg',
  'assets/images/dessert/dessert7.jpg',
  'assets/images/dessert/dessert6.jpg',
  'assets/images/dessert/dessert5.jpg',
  'assets/images/dessert/dessert4.jpg',
  'assets/images/dessert/dessert36.jpg',
  'assets/images/dessert/dessert35.jpg',
  'assets/images/dessert/dessert34.jpg',
  'assets/images/dessert/dessert33.jpg',
  'assets/images/dessert/dessert32.jpg',
  'assets/images/dessert/dessert31.jpg',
  'assets/images/dessert/dessert30.jpg',
  'assets/images/dessert/dessert3.jpg',
  'assets/images/dessert/dessert29.jpg',
  'assets/images/dessert/dessert28.jpg',
  'assets/images/dessert/dessert27.jpg',
  'assets/images/dessert/dessert26.jpg',
  'assets/images/dessert/dessert25.jpg',
  'assets/images/dessert/dessert24.jpg',
  'assets/images/dessert/dessert23.jpg',
  'assets/images/dessert/dessert22.jpg',
  'assets/images/dessert/dessert21.jpg',
  'assets/images/dessert/dessert20.jpg',
  'assets/images/dessert/dessert2.jpg',
  'assets/images/dessert/dessert19.jpg',
  'assets/images/dessert/dessert18.jpg',
  'assets/images/dessert/dessert17.jpg',
  'assets/images/dessert/dessert16.jpg',
  'assets/images/dessert/dessert15.jpg',
  'assets/images/dessert/dessert14.jpg',
  'assets/images/dessert/dessert13.jpg',
  'assets/images/dessert/dessert12.jpg',
  'assets/images/dessert/dessert11.jpg',
  'assets/images/dessert/dessert10.jpg',
  'assets/images/dessert/dessert1.jpg',
  'assets/images/butter-chicken/butter-chicken9.jpg',
  'assets/images/butter-chicken/butter-chicken8.jpg',
  'assets/images/butter-chicken/butter-chicken7.jpg',
  'assets/images/butter-chicken/butter-chicken6.jpg',
  'assets/images/butter-chicken/butter-chicken5.jpg',
  'assets/images/butter-chicken/butter-chicken4.jpg',
  'assets/images/butter-chicken/butter-chicken3.jpg',
  'assets/images/butter-chicken/butter-chicken22.jpg',
  'assets/images/butter-chicken/butter-chicken21.jpg',
  'assets/images/butter-chicken/butter-chicken20.jpg',
  'assets/images/butter-chicken/butter-chicken2.jpg',
  'assets/images/butter-chicken/butter-chicken19.jpg',
  'assets/images/butter-chicken/butter-chicken18.jpg',
  'assets/images/butter-chicken/butter-chicken17.jpg',
  'assets/images/butter-chicken/butter-chicken16.jpg',
  'assets/images/butter-chicken/butter-chicken15.jpg',
  'assets/images/butter-chicken/butter-chicken14.jpg',
  'assets/images/butter-chicken/butter-chicken13.jpg',
  'assets/images/butter-chicken/butter-chicken12.jpg',
  'assets/images/butter-chicken/butter-chicken11.jpg',
  'assets/images/butter-chicken/butter-chicken10.jpg',
  'assets/images/butter-chicken/butter-chicken1.jpg',
  'assets/images/burger/burger9.jpg',
  'assets/images/burger/burger87.jpg',
  'assets/images/burger/burger86.jpg',
  'assets/images/burger/burger85.jpg',
  'assets/images/burger/burger84.jpg',
  'assets/images/burger/burger83.jpg',
  'assets/images/burger/burger82.jpg',
  'assets/images/burger/burger81.jpg',
  'assets/images/burger/burger80.jpg',
  'assets/images/burger/burger8.jpg',
  'assets/images/burger/burger79.jpg',
  'assets/images/burger/burger78.jpg',
  'assets/images/burger/burger77.jpg',
  'assets/images/burger/burger76.jpg',
  'assets/images/burger/burger75.jpg',
  'assets/images/burger/burger74.jpg',
  'assets/images/burger/burger73.jpg',
  'assets/images/burger/burger72.jpg',
  'assets/images/burger/burger71.jpg',
  'assets/images/burger/burger70.jpg',
  'assets/images/burger/burger7.jpg',
  'assets/images/burger/burger69.jpg',
  'assets/images/burger/burger68.jpg',
  'assets/images/burger/burger67.jpg',
  'assets/images/burger/burger66.jpg',
  'assets/images/burger/burger65.jpg',
  'assets/images/burger/burger64.jpg',
  'assets/images/burger/burger63.jpg',
  'assets/images/burger/burger62.jpg',
  'assets/images/burger/burger61.jpg',
  'assets/images/burger/burger60.jpg',
  'assets/images/burger/burger6.jpg',
  'assets/images/burger/burger59.jpg',
  'assets/images/burger/burger58.jpg',
  'assets/images/burger/burger57.jpg',
  'assets/images/burger/burger56.jpg',
  'assets/images/burger/burger55.jpg',
  'assets/images/burger/burger54.jpg',
  'assets/images/burger/burger53.jpg',
  'assets/images/burger/burger52.jpg',
  'assets/images/burger/burger51.jpg',
  'assets/images/burger/burger50.jpg',
  'assets/images/burger/burger5.jpg',
  'assets/images/burger/burger49.jpg',
  'assets/images/burger/burger48.jpg',
  'assets/images/burger/burger47.jpg',
  'assets/images/burger/burger46.jpg',
  'assets/images/burger/burger45.jpg',
  'assets/images/burger/burger44.jpg',
  'assets/images/burger/burger43.jpg',
  'assets/images/burger/burger42.jpg',
  'assets/images/burger/burger41.jpg',
  'assets/images/burger/burger40.jpg',
  'assets/images/burger/burger4.jpg',
  'assets/images/burger/burger39.jpg',
  'assets/images/burger/burger38.jpg',
  'assets/images/burger/burger37.jpg',
  'assets/images/burger/burger36.jpg',
  'assets/images/burger/burger35.jpg',
  'assets/images/burger/burger34.jpg',
  'assets/images/burger/burger33.jpg',
  'assets/images/burger/burger32.jpg',
  'assets/images/burger/burger31.jpg',
  'assets/images/burger/burger30.jpg',
  'assets/images/burger/burger3.jpg',
  'assets/images/burger/burger29.jpg',
  'assets/images/burger/burger28.jpg',
  'assets/images/burger/burger27.jpg',
  'assets/images/burger/burger26.jpg',
  'assets/images/burger/burger25.jpg',
  'assets/images/burger/burger24.jpg',
  'assets/images/burger/burger23.jpg',
  'assets/images/burger/burger22.jpg',
  'assets/images/burger/burger21.jpg',
  'assets/images/burger/burger20.jpg',
  'assets/images/burger/burger2.jpg',
  'assets/images/burger/burger19.jpg',
  'assets/images/burger/burger18.jpg',
  'assets/images/burger/burger17.jpg',
  'assets/images/burger/burger16.jpg',
  'assets/images/burger/burger15.jpg',
  'assets/images/burger/burger14.jpg',
  'assets/images/burger/burger13.jpg',
  'assets/images/burger/burger12.jpg',
  'assets/images/burger/burger11.jpg',
  'assets/images/burger/burger10.jpg',
  'assets/images/burger/burger1.jpg',
  'assets/images/biryani/biryani9.jpg',
  'assets/images/biryani/biryani81.jpg',
  'assets/images/biryani/biryani80.jpg',
  'assets/images/biryani/biryani8.jpg',
  'assets/images/biryani/biryani79.jpg',
  'assets/images/biryani/biryani78.jpg',
  'assets/images/biryani/biryani77.jpg',
  'assets/images/biryani/biryani76.jpg',
  'assets/images/biryani/biryani75.jpg',
  'assets/images/biryani/biryani74.jpg',
  'assets/images/biryani/biryani73.jpg',
  'assets/images/biryani/biryani72.jpg',
  'assets/images/biryani/biryani71.jpg',
  'assets/images/biryani/biryani70.jpg',
  'assets/images/biryani/biryani7.jpg',
  'assets/images/biryani/biryani69.jpg',
  'assets/images/biryani/biryani68.jpg',
  'assets/images/biryani/biryani67.jpg',
  'assets/images/biryani/biryani66.jpg',
  'assets/images/biryani/biryani65.jpg',
  'assets/images/biryani/biryani64.jpg',
  'assets/images/biryani/biryani63.jpg',
  'assets/images/biryani/biryani62.jpg',
  'assets/images/biryani/biryani61.jpg',
  'assets/images/biryani/biryani60.jpg',
  'assets/images/biryani/biryani6.jpg',
  'assets/images/biryani/biryani59.jpg',
  'assets/images/biryani/biryani58.jpg',
  'assets/images/biryani/biryani57.jpg',
  'assets/images/biryani/biryani56.jpg',
  'assets/images/biryani/biryani55.jpg',
  'assets/images/biryani/biryani54.jpg',
  'assets/images/biryani/biryani53.jpg',
  'assets/images/biryani/biryani52.jpg',
  'assets/images/biryani/biryani51.jpg',
  'assets/images/biryani/biryani50.jpg',
  'assets/images/biryani/biryani5.jpg',
  'assets/images/biryani/biryani49.jpg',
  'assets/images/biryani/biryani48.jpg',
  'assets/images/biryani/biryani47.jpg',
  'assets/images/biryani/biryani46.jpg',
  'assets/images/biryani/biryani45.jpg',
  'assets/images/biryani/biryani44.jpg',
  'assets/images/biryani/biryani43.jpg',
  'assets/images/biryani/biryani42.jpg',
  'assets/images/biryani/biryani41.jpg',
  'assets/images/biryani/biryani40.jpg',
  'assets/images/biryani/biryani4.jpg',
  'assets/images/biryani/biryani39.jpg',
  'assets/images/biryani/biryani38.jpg',
  'assets/images/biryani/biryani37.jpg',
  'assets/images/biryani/biryani36.jpg',
  'assets/images/biryani/biryani35.jpg',
  'assets/images/biryani/biryani34.jpg',
  'assets/images/biryani/biryani33.jpg',
  'assets/images/biryani/biryani32.jpg',
  'assets/images/biryani/biryani31.jpg',
  'assets/images/biryani/biryani30.jpg',
  'assets/images/biryani/biryani3.jpg',
  'assets/images/biryani/biryani29.jpg',
  'assets/images/biryani/biryani28.jpg',
  'assets/images/biryani/biryani27.jpg',
  'assets/images/biryani/biryani26.jpg',
  'assets/images/biryani/biryani25.jpg',
  'assets/images/biryani/biryani24.jpg',
  'assets/images/biryani/biryani23.jpg',
  'assets/images/biryani/biryani22.jpg',
  'assets/images/biryani/biryani21.jpg',
  'assets/images/biryani/biryani20.jpg',
  'assets/images/biryani/biryani2.jpg',
  'assets/images/biryani/biryani19.jpg',
  'assets/images/biryani/biryani18.jpg',
  'assets/images/biryani/biryani17.jpg',
  'assets/images/biryani/biryani16.jpg',
  'assets/images/biryani/biryani15.jpg',
  'assets/images/biryani/biryani14.jpg',
  'assets/images/biryani/biryani13.jpg',
  'assets/images/biryani/biryani12.jpg',
  'assets/images/biryani/biryani11.jpg',
  'assets/images/biryani/biryani10.jpg',
  'assets/images/biryani/biryani1.jpg',
];

document.addEventListener('DOMContentLoaded', () => {
    const catImage = document.getElementById('cat-image');
    const foodSlots = document.getElementById('food-slots');
    const scoreDisplay = document.getElementById('score');
    const catContainer = document.getElementById('cat-container');

    let score = 0;
    let draggedFood = null;

    const getRandomFood = () => foodImagePaths[Math.floor(Math.random() * foodImagePaths.length)];

    const getNewCat = async () => {
        try {
            const response = await fetch('/api/images/search');
            const data = await response.json();
            catImage.src = data[0].url;
        } catch (error) {
            console.error('Error fetching cat image:', error);
        }
    };

    const showEmotion = (emoji) => {
        const emotion = document.createElement('div');
        emotion.classList.add('emotion');
        emotion.textContent = emoji;
        emotion.style.left = `${Math.random() * 50 + 25}%`;
        emotion.style.top = '20%';

        catContainer.appendChild(emotion);

        setTimeout(() => {
            emotion.remove();
        }, 1500);
    };

    const handleDrop = () => {
        const emojis = ['❤️', '🤢', '🤮', '😿', '😻'];
        const randomEmoji = emojis[Math.floor(Math.random() * emojis.length)];

        showEmotion(randomEmoji);

        if (randomEmoji === '❤️' || randomEmoji === '😻') {
            score++;
            scoreDisplay.textContent = `Удовольствие кота: ${'❤️'.repeat(score)}`;
        } 
        else if (score > 0 && (randomEmoji === '🤢' || randomEmoji === '🤮')) { // ✅ Fixed parentheses
            score--;
            // Simplified logic: just repeat hearts. If score is 0, repeat(0) returns "" (empty string).
            scoreDisplay.textContent = `Удовольствие кота: ${'❤️'.repeat(score)}`;
            
            // Optional: Add a message if the cat is unhappy/empty
            if (score === 0) {
                scoreDisplay.textContent = `Удовольствие кота: 0 😿`;
            }
        }
        // Optional: Handle neutral emojis like '😿' if needed

        if (score >= 3) {
            // 1. Disable interaction temporarily (optional, but recommended)
            // dropArea.classList.add('disabled'); 

            // 2. Show the "Love" message immediately or after a tiny delay
            scoreDisplay.textContent = `Котик вас любит! 😻`;
            
            // 3. Wait 1 second (1000 ms), then reset
            setTimeout(() => {
                score = 0;
                scoreDisplay.textContent = `Удовольствие кота: ${'❤️'.repeat(score)}`; // Will show empty string or handle 0 case
                getNewCat();
                
                // Re-enable interaction if you disabled it
                // dropArea.classList.remove('disabled');
            }, 1000);
        }

        // Replace the used food
        draggedFood.src = getRandomFood();
    };

    const createFoodSlots = () => {
        for (let i = 0; i < 5; i++) {
            const foodItem = document.createElement('img');
            foodItem.classList.add('food-item');
            foodItem.src = getRandomFood();
            foodItem.draggable = true;
            foodItem.id = `food-${i}`;

            foodItem.addEventListener('dragstart', (e) => {
                draggedFood = e.target;
            });

            foodSlots.appendChild(foodItem);
        }
    };

    catImage.addEventListener('dragover', (e) => {
        e.preventDefault();
    });

    catImage.addEventListener('drop', (e) => {
        e.preventDefault();
        handleDrop();
    });

    getNewCat();
    createFoodSlots();
});
